import Head from "next/head";
import { Card, CardContent, Container, Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container
          sx={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
          }}
          maxWidth="lg"
        >
          <Card sx={{ maxWidth: 392, maxHeight: 400 }}>
            <CardContent>
              <Typography variant="h1">Hello, World!</Typography>
            </CardContent>
          </Card>
        </Container>
      </main>
    </>
  );
}
